Side by side verification

diff --git a/initramfs/initramfs-tools/scripts/local-top/top-verity b/initramfs/initramfs-tools/scripts/local-top/top-verity
--- a/initramfs/initramfs-tools/scripts/local-top/top-verity
+++ b/initramfs/initramfs-tools/scripts/local-top/top-verity
@@ -70,6 +70,26 @@ if [ $SETTINGS_COUNT -ne 4 ]; then
     exit 1
 fi
 
+#### TEMP DEBUG
+lsblk
+
+echo "Verifying data disk"
+ret=0
+veritysetup --verbose --debug verify /dev/sdc1 /dev/sdc2 "$VERITYHASH" || ret=$?
+if [ $ret -ne 0 ]; then
+    echo "veritysetup verification failed!"
+    exit 1
+fi
+
+echo "Verifying OS disk"
+ret=0
+veritysetup --verbose --debug verify /dev/sda1 /dev/sda2 "$VERITYHASH" || ret=$?
+if [ $ret -ne 0 ]; then
+    echo "veritysetup verification failed!"
+    exit 1
+fi
+####
+
 echo "Verifying verity hashes"
 ret=0
 veritysetup --verbose --debug verify "$VERITYDATADEV" "$VERITYTREEDEV" "$VERITYHASH" || ret=$?
