Double check that it works now

diff --git a/initramfs/initramfs-tools/scripts/local-top/top-verity b/initramfs/initramfs-tools/scripts/local-top/top-verity
--- a/initramfs/initramfs-tools/scripts/local-top/top-verity
+++ b/initramfs/initramfs-tools/scripts/local-top/top-verity
@@ -71,13 +71,13 @@ if [ $SETTINGS_COUNT -ne 4 ]; then
 fi
 
 #### TEMP DEBUG
-echo "Verifying data disk"
-ret=0
-veritysetup --verbose --debug verify /dev/disk/azure/scsi1/lun0-part1 /dev/disk/azure/scsi1/lun0-part2 "$VERITYHASH" || ret=$?
-if [ $ret -ne 0 ]; then
-    echo "veritysetup verification failed!"
-    exit 1
-fi
+#echo "Verifying data disk"
+#ret=0
+#veritysetup --verbose --debug verify /dev/disk/azure/scsi1/lun0-part1 /dev/disk/azure/scsi1/lun0-part2 "$VERITYHASH" || ret=$?
+#if [ $ret -ne 0 ]; then
+#    echo "veritysetup verification failed!"
+#    exit 1
+#fi
 
 echo "Verifying OS disk"
 ret=0
@@ -86,6 +86,8 @@ if [ $ret -ne 0 ]; then
     echo "veritysetup verification failed!"
     exit 1
 fi
+
+exit 0
 ####
 
 echo "Verifying verity hashes"
